n_nations = 1;
baseSensorCapability = 500;
initialSensorsRange = [10 10];
sensorReqRateStats = [1 0]; % years
sensorConSpeedStats = [3 0]; % years
dataQualityStats = [1 0];
initialSatsRange = [160 160]; 
initialGssnMemberChance = 0;
minGssnDQ = 0.8;
gssnFee = 2000; % million $ / year